version: '3'

x-template: &flyway-template
  image: boxfuse/flyway:latest
  volumes:
    - .:/flyway/sql
    - .:/flyway/conf
  depends_on:
    - db

services:

  elasticsearch: # Elasticsearch Instance
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic
      - ingress
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5601:5601"
    networks:
      - elastic
      - ingress

  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  db:
    container_name: db
    images: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - elastic
      - ingress

volumes: # Define seperate volume for Elasticsearch data
  esdata:

networks:
  elastic:
  ingress: